														--COMANDO PARA CRIAR BANCO DE DADOS
CREATE DATABASE MIF1AN;

															--COMANDO PARA USAR O BD
USE MIF1AN;													
	
																--CRIAR TABELA 
CREATE TABLE ALUNO (									-- ABRIR E FECHAR PARETESES SEMPRE
COD_ALUNO INT PRIMARY KEY,
NOME VARCHAR(50),
SEXO CHAR (1) ) ;
														-- CONSULTAR DADOS DA TABELA

 SELECT  * FROM ALUNO;								  -- SELECIONE TODAS AS COLUNAS DA TABELA ALUNO
														-- INSERIR DADOS NA TABELA
 INSERT INTO ALUNO VALUES ( 1,'ANTONIO','M'); 
 INSERT INTO ALUNO VALUES ( 2,'PAULO', 'M'); 
 INSERT INTO ALUNO VALUES ( 3,'EDUARDA','F'); 
 INSERT INTO ALUNO VALUES ( 4,'ANGELA', 'F');  
 INSERT INTO ALUNO VALUES ( 5,'AGATHA', 'F');  
 INSERT INTO ALUNO VALUES ( 6,'JEFERSON', 'M'); 


																--APAGAR REGISTROS
 DELETE FROM ALUNO;
																--APAGAR TABELA
 DROP TABLE ALUNO;

																--CONSULTA COM FILTRO
SELECT * FROM ALUNO WHERE SEXO = 'F';

SELECT * FROM ALUNO WHERE SEXO = 'M';     

SELECT * FROM ALUNO WHERE COD_ALUNO = '3' OR COD_ALUNO= '5'

SELECT * FROM ALUNO WHERE NOME = 'AGATHA';

SELECT NOME, SEXO  FROM ALUNO;

USE MEUPET;
SELECT * FROM CLIENTE_W3 ;