SELECT * FROM CLIENTE




SELECT CLIENTE.CODCLI,
	CLIENTE.NOME,
	CLIENTE.CIDADE, 
	VENDA.DUPLIC, 
	VENDA.VENCTO, 
	VENDA.VALOR 
FROM CLIENTE JOIN VENDA 
ON (CLIENTE.CODCLI = VENDA. CODCLI)
WHERE CLIENTE.ESTADO = 'SP'

SELECT C.CODCLI,
	C.NOME,
	C.CIDADE, 
	V.DUPLIC, 
	V.VENCTO, 
	V.VALOR 
FROM CLIENTE C JOIN VENDA V
ON (C.CODCLI = V. CODCLI)
WHERE C.ESTADO = 'SP'


 SELECT C.CODCLI,
	C.NOME,
	C.ESTADO, 
	V.VENCTO, 
	V.VALOR,
	V.DUPLIC
FROM CLIENTE C JOIN VENDA V
ON (C.CODCLI = V. CODCLI)
WHERE MONTH (V.VENCTO ) = 10
ORDER BY NOME DESC

 
 
 SELECT DATENAME( MONTH,V.VENCTO),
	SUM (V.VALOR) AS TOTAL
FROM CLIENTE C JOIN VENDA V
ON (C.CODCLI = V. CODCLI)
GROUP BY  DATENAME( MONTH,V.VENCTO)

 
 SELECT DATENAME( MONTH,V.VENCTO),
	SUM (V.VALOR) AS TOTAL
FROM CLIENTE C JOIN VENDA V
ON (C.CODCLI = V. CODCLI)
GROUP BY MONTH (V.VENCTO),
DATENAME( MONTH,V.VENCTO)
ORDER BY 
MONTH (V.VENCTO)


SELECT COUNT(NOME) FROM CLIENTE
WHERE CEP LIKE '%010'

SELECT COUNT(NOME) FROM CLIENTE
WHERE RIGHT (CEP,3) = '010'


SELECT	cliente.CODCLI,
		CLIENTE.NOME,
		VENDA.VENCTO,
		VENDA.VALOR
		FROM CLIENTE JOIN VENDA ON
		(CLIENTE.CODCLI= VENDA.CODCLI)
		WHERE VENDA.VALOR BETWEEN 3000 AND 6000