

SELECT NOME, ENDERECO, CIDADE, ESTADO 
	FROM CLIENTE
	WHERE ESTADO IN ('SP', 'MG');

CREATE VIEW CAFE_COM_LEITE AS 
SELECT NOME, ENDERECO, CIDADE, ESTADO 
	FROM CLIENTE
	WHERE ESTADO IN ('SP', 'MG');

	SELECT * FROM CAFE_COM_LEITE
	WHERE ESTADO = 'SP' 

	CREATE VIEW CAFE_COM_LEITE AS 
SELECT NOME, ENDERECO, CIDADE, ESTADO 
	FROM CLIENTE
	WHERE ESTADO IN ('SP', 'MG', 'BA');


	CREATE PROCEDURE SP_CLIENTES AS 
	SELECT NOME, ENDERECO, CIDADE, CIDADE 
	FROM CLIENTE
	WHERE ESTADO IN ('SP', 'MG');
	  

	  --EXECUTANDO UM STORED PROCIDER

	EXECUTE SP_CLIENTES;

	--CRIANDO OUTRA STORED PROCEDURE

 	CREATE PROCEDURE SP_BARUERI  (@EST CHAR (2) )AS 
	SELECT NOME, ENDERECO, CIDADE, CIDADE 
	FROM CLIENTE
	WHERE ESTADO = @EST;

	EXECUTE SP_BARUERI 'SP'

	CREATE PROCEDURE SP_P3 (@EST CHAR (2)) AS
	IF @EST = 'MG'
	   PRINT 'MINAS NÃO'

	ELSE 
	SELECT NOME, ENDERECO, CIDADE,ESTADO 
	FROM CLIENTE
	WHERE ESTADO = @EST;

	EXEC SP_P3'MG'

	ALTER PROCEDURE MOSTRA_MAIOR 
	
	(@NUM1 INT, @NUM2 INT) AS
	 
	 IF @NUM1 > @NUM2
		PRINT 'O MAIOR É : ' +  CONVERT(VARCHAR,@NUM1)
	 ELSE 
		PRINT 'O MAIOR É : ' +  CONVERT(VARCHAR,@NUM2)

	EXECUTE MOSTRA_MAIOR 15,8


		ALTER PROCEDURE MOSTRA_MAIOR 
	
	(@NUM1 INT, @NUM2 INT) AS
	 
	 IF @NUM1 > @NUM2
	 BEGIN
		PRINT 'O MAIOR É : ' +  CONVERT(VARCHAR,@NUM1)
		PRINT 'PASOSOU PELO PRIMEIRO BLOCO'
	END
	 ELSE 
		PRINT 'O MAIOR É : ' +  CONVERT(VARCHAR,@NUM2)

	EXECUTE MOSTRA_MAIOR 15,8