/* CRIA A BASE DE DADOS EMPRESA_FIEB*/
CREATE DATABASE EMPRESA_FIEB

/*UTILIZA A BASE DE DADOS EMPRESA_FIEB*/
USE EMPRESA_FIEB

/* CRIA A TABELA DEPARTAMENTO */
CREATE TABLE DEPARTAMENTO
(
	ID_DEPTO INT,
	DESCRICAO VARCHAR(50) NOT NULL,
	CONSTRAINT PK_DEPTO PRIMARY KEY (ID_DEPTO)
);

/* INSERE DADOS NA TABELA DEPARTAMENTO */
INSERT INTO DEPARTAMENTO (ID_DEPTO, DESCRICAO) VALUES (1, 'FÁBRICA DE SOFTWARE');
INSERT INTO DEPARTAMENTO (ID_DEPTO, DESCRICAO) VALUES (2, 'RECURSOS HUMANOS');
INSERT INTO DEPARTAMENTO (ID_DEPTO, DESCRICAO) VALUES (3, 'FINANCEIRO');

/* CRIA A TABELA FUNCIONARIO */
CREATE TABLE FUNCIONARIO
(
	ID_FUNC INT IDENTITY (1,1),
	NOME VARCHAR(50) NOT NULL,
	DATA_NASC DATE NOT NULL,
	GENERO CHAR(1),
	ENDERECO VARCHAR(70) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	SALARIO DECIMAL(10,2) NOT NULL,
    ID_DEPTO INT,
	CONSTRAINT PK_FUNC PRIMARY KEY (ID_FUNC),
	CONSTRAINT CK_GENERO CHECK (GENERO='F' OR GENERO='M'),
	CONSTRAINT FK_DEPTO FOREIGN KEY (ID_DEPTO) REFERENCES DEPARTAMENTO (ID_DEPTO)
);


/* INSERE DADOS NA TABELA FUNCIONARIO */

INSERT INTO FUNCIONARIO (NOME, DATA_NASC, GENERO, ENDERECO, BAIRRO, CIDADE, ESTADO, SALARIO, ID_DEPTO) VALUES ('ANA MARIA LOPES CANDIDO', '25/05/1980', 'F','R. DA PRATA', 'JD BELEM', 'BARUERI', 'SP', 6000, 1);
INSERT INTO FUNCIONARIO (NOME, DATA_NASC, GENERO, ENDERECO, BAIRRO, CIDADE, ESTADO, SALARIO, ID_DEPTO) VALUES ('ROBERTO PEREIRA DIAS','02/04/1975','M','R. DAS PALMEIRAS', 'JD. SANTA CLARA', 'SÃO PAULO', 'SP', 10000, 1);
INSERT INTO FUNCIONARIO (NOME, DATA_NASC, GENERO, ENDERECO, BAIRRO, CIDADE, ESTADO, SALARIO, ID_DEPTO) VALUES ('CELIA REGINA AVARENGA','02/11/1975','F','R. DAS ROSAS', 'PARAÍSO', 'SÃO PAULO', 'SP', 8000, 1);
INSERT INTO FUNCIONARIO (NOME, DATA_NASC, GENERO, ENDERECO, BAIRRO, CIDADE, ESTADO, SALARIO, ID_DEPTO) VALUES ('LETICIA PATRICIA ARAUJO','02/04/1975','F','R. TERCEIRO', 'JD. TUPÃ', 'BARUERI', 'SP', 6000, 1);
INSERT INTO FUNCIONARIO (NOME, DATA_NASC, GENERO, ENDERECO, BAIRRO, CIDADE, ESTADO, SALARIO, ID_DEPTO) VALUES ('JOAO BATISTA MORGADO','05/04/1975','M','R. RUBIA', 'JD. SANTA CLARA', 'OSASCO', 'SP', 5000, 1);
INSERT INTO FUNCIONARIO (NOME, DATA_NASC, GENERO, ENDERECO, BAIRRO, CIDADE, ESTADO, SALARIO, ID_DEPTO) VALUES ('CARLOS ANTONIO COSTA','02/12/1975','M','R. DR. ANTONIO', 'JD. SANTA CLARA', 'OSASCO', 'SP', 5000, 1);
INSERT INTO FUNCIONARIO (NOME, DATA_NASC, GENERO, ENDERECO, BAIRRO, CIDADE, ESTADO, SALARIO, ID_DEPTO) VALUES ('JOSE VAGNER CESAR DE FREITAS','24/12/1984','M','R. DAS ANDORINHAS', 'JD. OUTONO', 'JANDIRA', 'SP', 1500, 1);
INSERT INTO FUNCIONARIO (NOME, DATA_NASC, GENERO, ENDERECO, BAIRRO, CIDADE, ESTADO, SALARIO, ID_DEPTO) VALUES ('ANTONIA DOS SANTOS','14/12/1984','F','R. DIAMANTES', 'JD. PRIMAVERA', 'OSASCO', 'SP', 5500, 1);
INSERT INTO FUNCIONARIO (NOME, DATA_NASC, GENERO, ENDERECO, BAIRRO, CIDADE, ESTADO, SALARIO, ID_DEPTO) VALUES ('BEATRIZ SOUZA', '02/03/1984','F','R. DAS ANDORINHAS', 'JD. OUTONO', 'BARUERI', 'SP', 7500, 1);

/* CRIA A TABELA PROJETO */
CREATE TABLE PROJETO
(
	ID_PROJ INT,
	NOME VARCHAR(50) NOT NULL,
	DATA_INICIO DATE NOT NULL,
	DATA_FIM DATE NULL,
	ID_GESTOR INT,
	CONSTRAINT PK_PROJ PRIMARY KEY (ID_PROJ),
    CONSTRAINT FK_GESTOR FOREIGN KEY (ID_GESTOR) REFERENCES FUNCIONARIO (ID_FUNC)
);

INSERT INTO PROJETO VALUES (1, 'REESTRUTURAÇÃO DE NOTA FISCAL ELETRÔNICA', '20/02/2009', '20/02/2010', 2);
INSERT INTO PROJETO VALUES (2, 'PROJETO DE MELHORIAS CONTÍNUAS', '01/02/2009', '02/05/2012', 3);

 /* CRIA A TABELA PROJETO X FUNCIONARIO*/
CREATE TABLE PROJ_FUNC
(
	ID_PROJ INT, 
	ID_FUNC INT, 
	CONSTRAINT PK_PROJ_FUNC PRIMARY KEY (ID_PROJ, ID_FUNC),
	CONSTRAINT FK_PROJETO FOREIGN KEY (ID_PROJ) REFERENCES PROJETO (ID_PROJ),
	CONSTRAINT FK_FUNCIONARIO FOREIGN KEY (ID_FUNC) REFERENCES FUNCIONARIO (ID_FUNC)
);

INSERT INTO PROJ_FUNC (ID_PROJ, ID_FUNC) VALUES (1, 1);
INSERT INTO PROJ_FUNC (ID_PROJ, ID_FUNC) VALUES (1, 5);
INSERT INTO PROJ_FUNC (ID_PROJ, ID_FUNC) VALUES (1, 6);
INSERT INTO PROJ_FUNC (ID_PROJ, ID_FUNC) VALUES (1, 7);
INSERT INTO PROJ_FUNC (ID_PROJ, ID_FUNC) VALUES (1, 8);
INSERT INTO PROJ_FUNC (ID_PROJ, ID_FUNC) VALUES (2, 9);
INSERT INTO PROJ_FUNC (ID_PROJ, ID_FUNC) VALUES (2, 5);
INSERT INTO PROJ_FUNC (ID_PROJ, ID_FUNC) VALUES (2, 6);
INSERT INTO PROJ_FUNC (ID_PROJ, ID_FUNC) VALUES (2, 7);



--ATIVIDADE PREPARATORIA--
--EX.1--
CREATE TABLE CARGO (
 ID_CARGO INT PRIMARY KEY,
 DESCRICAO VARCHAR(70)
--CONSTRAINT PK_CARGO PRIMARY KEY ID_CARGO
 );	


 ALTER TABLE CLIENTE add constraint CPF unique (CPF);

 --EX.2--
 ALTER TABLE FUNCIONARIO ADD ID_CARGO INT;
 ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_CARGO FOREIGN KEY(ID_CARGO) REFERENCES CARGO(ID_CARGO); 

 --EX3--
 INSERT INTO CARGO(ID_CARGO, DESCRICAO) VALUES (1, 'Gerente de Projeto');
  INSERT INTO CARGO(ID_CARGO, DESCRICAO) VALUES (2, 'Analista de Sistemas');
 INSERT INTO CARGO(ID_CARGO, DESCRICAO) VALUES (3, 'Desenvolvedor');
 INSERT INTO CARGO(ID_CARGO, DESCRICAO) VALUES (4, 'Analista de Teste');

--ex.4--

--ex.4-A
UPDATE FUNCIONARIO SET ID_CARGO = 1 
WHERE CIDADE IN ('São Paulo');


--ex.4-B
UPDATE FUNCIONARIO SET ID_CARGO = 2 
WHERE CIDADE IN ('Barueri');

--ex.4-C
UPDATE FUNCIONARIO SET ID_CARGO = 3 
WHERE CIDADE IN ('Osasco');

--ex.4-C
UPDATE FUNCIONARIO SET ID_CARGO = 4 
WHERE CIDADE IN ('Jandira');

--Ex.5--
SELECT SALARIO, NOME, ID_CARGO, ID_DEPTO  FROM FUNCIONARIO
WHERE SALARIO < (3000)

--EX.6--
DELETE DEPARTAMENTO
WHERE ID_DEPTO = 1;
--Não funciona porque é uma Foreing Key--
--Não funcionou pq existe uma referencia da tabela funcionario em outras tabelas. A forma de exclusão, só pode ser deletados, 
--se os funcionarios ou membros da coluna, forem exclusos das outras tabelas relacionadas.


--EX.7--
SELECT FUNCIONARIO.NOME, 
	   CARGO.DESCRICAO AS CARGO
FROM
	FUNCIONARIO INNER JOIN CARGO
	--INNER JOIN= só vai mostrar oq está relacionado das duas tabelas
	ON FUNCIONARIO.ID_CARGO = CARGO.ID_CARGO

--EX.8--
SELECT FUNCIONARIO.NOME, 
	   FUNCIONARIO.CIDADE,
	   CARGO.DESCRICAO AS CARGO
FROM
	FUNCIONARIO INNER JOIN CARGO
	ON FUNCIONARIO.ID_CARGO = CARGO.ID_CARGO
WHERE CIDADE IN ('São Paulo','Barueri')
--OU USO OUTRO WHERE
--WHERE CIDADE = ('BARUERI')

--EX.9--
SELECT CARGO.DESCRICAO AS CARGO, COUNT(DESCRICAO)
FROM FUNCIONARIO INNER JOIN CARGO
ON FUNCIONARIO.ID_CARGO = CARGO.ID_CARGO
GROUP BY CARGO.DESCRICAO

	
  
	FUNCIONARIO;
select *from FUNCIONARIO