CREATE DATABASE EVOBODY
USE EVOBODY


CREATE TABLE CLIENTE (
COD_CLIENTE INT,
CPF VARCHAR (11),
NOME VARCHAR (20),
SOBRENOME VARCHAR (30),
TELEFONE VARCHAR (10)
CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_CLIENTE)
);

CREATE TABLE ENDERECO 
(COD_ENDERECO INT,
ESTADO CHAR (20),
CIDADE VARCHAR (20),
LOGRADOURO VARCHAR (50),
CEP VARCHAR (8),
NÚMERO_RES INT,
COD_CLIENTE INT
CONSTRAINT PK_ENDERECO PRIMARY KEY (COD_ENDERECO)
CONSTRAINT FK_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE)
);

CREATE TABLE PEDIDO 
(COD_PEDIDO INT,
DATA_ENTREGA DATETIME,
DATA_EMISSAO DATE,
DATA_PEDIDO DATETIME,
VALOR_NOTA INT,
COD_CLIENTE INT
CONSTRAINT PK_PEDIDO PRIMARY KEY (COD_PEDIDO)
CONSTRAINT FK_CLIENT FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE)
);

CREATE TABLE PRODUTO (
COD_PRODUTO INT,
CATEGORIA VARCHAR (20) NOT NULL,
PRECO CHAR (5),
ESTOQUE VARCHAR (30),
QNTD INT
CONSTRAINT PK_PRODUTO PRIMARY KEY (COD_PRODUTO)
);

CREATE TABLE ITEM_PEDIDO (
COD_ITEM_PEDIDO INT,
COD_PRODUTO INT,
QNTD INT,
COD_PEDIDO INT, 
CONSTRAINT PK_ITEM_PEDIDO PRIMARY KEY (COD_ITEM_PEDIDO),
CONSTRAINT FK_PEDIDO FOREIGN KEY (COD_PEDIDO) REFERENCES PEDIDO (COD_PEDIDO),
CONSTRAINT FK_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO)
);


ALTER TABLE ITEM_PEDIDO ADD CONSTRAINT FK_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO)
 
 USE  master
 DROP DATABASE EVOBODY 